### ISSUE TITLE
ESP8266 MD5 Fatal error

### ISSUE THREAD

**Issue by alexandrglm** [simtcrom/arduino#1]
Hi,

I'm experiencing Error Code 2 and MD5 mismatch errors when trying to flash firmware to my ESP8266 board, similar to your issue described [here](https://github.com/espressif/esptool/issues/662#issuecomment-2198445072).

I'm using the same board (with an integrated OLED that cannot be detached). I've seen that the Espressif team doesn't often respond to users with "generic" Chinese development boards, so I'm hesitant to post on their official issue thread.

Have you found a solution for this problem with your board? Any help would be greatly appreciated.

Thanks.
Alexandr.

**Comment by simtcrom** [comment]
Nope. The seller replaced my board.

**Comment by alexandrglm** [comment]
Thanks for the response.

 I'll try with a replacement if the flashing settings I was looking for in order to restore the board don't work.

Alexandr.
